### ISSUE TITLE
agenda knob open full screen bug  => (chooseDay)

### ISSUE THREAD

**Issue by angularbaby** [wix/react-native-calendars#106]
I am very fond of this agenda, but i after use knob open full screen across the month selsect，click chooseDay(new Date()),There will be a bug ,header correct，but bottom list no locate the correct

**Comment by tautvilas** [comment]
can you give a code snippet to reproduce the bug? also what platform/device you are using?

**Comment by angularbaby** [comment]
`import React from "react";
import { Text, View, TouchableOpacity } from "react-native";
import styles from "./style";
import { Icon } from "../../../components";
import {
  mainBlue,
  minorGreen,
  minorOrange,
  minorRed,
  white
} from "../../../colors";
import { Agenda } from "react-native-calendars";

class Schedule extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      items: {},
      selected: new Date(),
    };
  }

  render() {
    return (
      <View style={{ flex: 1 }}>
        <Agenda
          ref={agenda => {
            this.agenda = agenda;
          }}
          items={this.state.items}
          loadItemsForMonth={this.loadItems.bind(this)}
          selected={this.state.selected}
          renderItem={this.renderItem.bind(this)}
          renderEmptyDate={this.renderEmptyDate.bind(this)}
          rowHasChanged={this.rowHasChanged.bind(this)}
          // monthFormat={'yyyy'}
          //theme={{calendarBackground: 'red'}}
          //renderDay={(day, item) => (<Text>{day ? day.day: 'item'}</Text>)}
        />
        <View style={styles.refreshIcon}>
          <TouchableOpacity onPress={() => this.agenda.chooseDay(new Date())}>
            <Icon.Circle
              type="refresh"
              size={40}
              color={white}
              backgroundColor={minorOrange}
            />
          </TouchableOpacity>
        </View>
      </View>
    );
  }

  loadItems(day) {
    setTimeout(() => {
      for (let i = -15; i < 85; i++) {
        const time = day.timestamp + i * 24 * 60 * 60 * 1000;
        const strTime = this.timeToString(time);
        if (!this.state.items[strTime]) {
          this.state.items[strTime] = [];
          const numItems = Math.floor(Math.random() * 5);
          for (let j = 0; j < numItems; j++) {
            eval(
              "var word=" +
                '"\\u' +
                (Math.round(Math.random() * 20901) + 19968).toString(16) +
                '"'
            );
            this.state.items[strTime].push({
              title: "五月份农户可能有贷款，再去看看",
              subTitle:
                "时间：" +
                Math.ceil(Math.random() * 24) +
                ":00   客户：张" +
                word +
                word,
              state: Math.ceil(Math.random() * 4)
            });
          }
        }
      }
      //console.log(this.state.items);
      const newItems = {};
      Object.keys(this.state.items).forEach(key => {
        newItems[key] = this.state.items[key];
      });
      this.setState({
        items: newItems
      });
    }, 1000);
    // console.log(`Load Items for ${day.year}-${day.month}`);
  }

  renderItem(item) {
    console.log(item.state);
    let color = minorRed;
    switch (item.state) {
      case 1:
        color = minorRed;
        break;
      case 2:
        color = minorGreen;
        break;
      case 3:
        color = minorOrange;
        break;
      case 4:
        color = mainBlue;
        break;
    }
    let style = {
      backgroundColor: color
    };
    return (
      <View style={styles.item}>
        <View style={[styles.badge, style]} />
        <View>
          <Text style={styles.title}>
            {item.title}
          </Text>
        </View>
        <View>
          <Text style={styles.subTitle}>
            {item.subTitle}
          </Text>
        </View>
        <View style={styles.operation}>
          <Text style={styles.operationText}>
            <Icon type="check-route" size={14} color={mainBlue} /> 查看路线
          </Text>
        </View>
      </View>
    );
  }

  renderEmptyDate() {
    return (
      <View style={styles.item}>
        <View style={styles.noScheduleView}>
          <View>
            <Icon type="noData" size={60} color={"#D8D8D8"} />
          </View>
          <TouchableOpacity>
            <View style={styles.addSchBtn}>
              <Text style={styles.addSchBtnText}>创建该日日程</Text>
            </View>
          </TouchableOpacity>
        </View>
      </View>
    );
  }

  rowHasChanged(r1, r2) {
    return r1.name !== r2.name;
  }

  timeToString(time) {
    const date = new Date(time);
    return date.toISOString().split("T")[0];
  }
}

export default Schedule;
`

**Comment by angularbaby** [comment]
![login](https://user-images.githubusercontent.com/19659056/28409121-3e518ee2-6d6c-11e7-8757-e2df66105bc5.gif)

**Comment by angularbaby** [comment]
`<View style={{ flex: 1 }}>
        <Agenda
          ref={agenda => {
            this.agenda = agenda;
          }}
          items={this.state.items}
          loadItemsForMonth={this.loadItems.bind(this)}
          selected={this.state.selected}
          renderItem={this.renderItem.bind(this)}
          renderEmptyDate={this.renderEmptyDate.bind(this)}
          rowHasChanged={this.rowHasChanged.bind(this)}
          // monthFormat={'yyyy'}
          //theme={{calendarBackground: 'red'}}
          //renderDay={(day, item) => (<Text>{day ? day.day: 'item'}</Text>)}
        />
        <View style={styles.refreshIcon}>
          <TouchableOpacity onPress={() => this.agenda.chooseDay(new Date())}>
            <Icon.Circle
              type="refresh"
              size={40}
              color={white}
              backgroundColor={minorOrange}
            />
          </TouchableOpacity>
        </View>
      </View>`
### react-native ios

**Comment by angularbaby** [comment]
![image](https://user-images.githubusercontent.com/19659056/28409292-ce8358d8-6d6c-11e7-9dc1-240697c77699.png)

**Comment by jkomyno** [comment]
@angularbaby can you please provide a gist snippet instead of a screenshot?

**Comment by angularbaby** [comment]
import React from "react";
import { Text, View, TouchableOpacity,PanResponder } from "react-native";
import styles from "./style";
import { Icon } from "../../../components";
import {
  mainBlue,
  minorGreen,
  minorOrange,
  minorRed,
  white
} from "../../../colors";
import { Agenda } from "react-native-calendars";
import Swipeout from "react-native-swipeout";

class Schedule extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      items: {},
      selected: new Date()
    };
  }

  render() {
    return (
      <View style={{ flex: 1 }}>
        <Agenda
          ref={agenda => {
            this.agenda = agenda;
          }}
          items={this.state.items}
          loadItemsForMonth={this.loadItems.bind(this)}
          selected={this.state.selected}
          renderItem={this.renderItem.bind(this)}
          renderEmptyDate={this.renderEmptyDate.bind(this)}
          rowHasChanged={this.rowHasChanged.bind(this)}
        />
        <View style={styles.refreshIcon}>
          <TouchableOpacity onPress={() => this.agenda.chooseDay(new Date())}>
            <Icon.Circle
              type="refresh"
              size={40}
              color={white}
              backgroundColor={minorOrange}
            />
          </TouchableOpacity>
        </View>
      </View>
    );
  }

  loadItems(day) {
    setTimeout(() => {
      for (let i = -15; i < 85; i++) {
        const time = day.timestamp + i * 24 * 60 * 60 * 1000;
        const strTime = this.timeToString(time);
        if (!this.state.items[strTime]) {
          this.state.items[strTime] = [];
          const numItems = Math.floor(Math.random() * 5);
          for (let j = 0; j < numItems; j++) {
            eval(
              "var word=" +
                '"\\u' +
                (Math.round(Math.random() * 20901) + 19968).toString(16) +
                '"'
            );
            this.state.items[strTime].push({
              title: "五月份农户可能有贷款啊",
              subTitle:
                "时间：" +
                Math.ceil(Math.random() * 24) +
                ":00   客户：张" +
                word +
                word,
              state: Math.ceil(Math.random() * 4)
            });
          }
        }
      }
      //console.log(this.state.items);
      const newItems = {};
      Object.keys(this.state.items).forEach(key => {
        newItems[key] = this.state.items[key];
      });
      this.setState({
        items: newItems
      });
    }, 1000);
    // console.log(`Load Items for ${day.year}-${day.month}`);
  }
  renderItem(item) {
    console.log(item.state);
    let color = minorRed;
    switch (item.state) {
      case 1:
        color = minorRed;
        break;
      case 2:
        color = minorGreen;
        break;
      case 3:
        color = minorOrange;
        break;
      case 4:
        color = mainBlue;
        break;
    }
    let style = {
      backgroundColor: color
    };
    // Buttons
    let swipeoutBtns = [
      {
        text: "删除",
        backgroundColor:minorRed
      }
    ];
    return (
      <View style={styles.item}>
        <Swipeout right={swipeoutBtns} backgroundColor={white}>
          <View style={[styles.badge, style]} />
          <View>
            <Text style={styles.title}>
              {item.title}
            </Text>
          </View>
          <View>
            <Text style={styles.subTitle}>
              {item.subTitle}
            </Text>
          </View>
          <View>
            <View style={styles.operation}>
              <Text style={styles.operationText}>
                <Icon type="check-route" size={14} color={mainBlue} /> 查看路线
              </Text>
            </View>
          </View>
        </Swipeout>
      </View>
    );
  }

  renderEmptyDate() {
    return (
      <View style={styles.item}>
        <View style={styles.noScheduleView}>
          <View>
            <Icon type="noData" size={40} color={"#D8D8D8"} />
          </View>
          <TouchableOpacity>
            <View style={styles.addSchBtn}>
              <Text style={styles.addSchBtnText}>创建该日日程</Text>
            </View>
          </TouchableOpacity>
        </View>
      </View>
    );
  }

  rowHasChanged(r1, r2) {
    return r1.name !== r2.name;
  }

  timeToString(time) {
    const date = new Date(time);
    return date.toISOString().split("T")[0];
  }
}

export default Schedule;

**Comment by angularbaby** [comment]
`import React from "react";
import { Text, View, TouchableOpacity,PanResponder } from "react-native";
import styles from "./style";
import { Icon } from "../../../components";
import {
  mainBlue,
  minorGreen,
  minorOrange,
  minorRed,
  white
} from "../../../colors";
import { Agenda } from "react-native-calendars";
import Swipeout from "react-native-swipeout";

class Schedule extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      items: {},
      selected: new Date()
    };
  }

  render() {
    return (
      <View style={{ flex: 1 }}>
        <Agenda
          ref={agenda => {
            this.agenda = agenda;
          }}
          items={this.state.items}
          loadItemsForMonth={this.loadItems.bind(this)}
          selected={this.state.selected}
          renderItem={this.renderItem.bind(this)}
          renderEmptyDate={this.renderEmptyDate.bind(this)}
          rowHasChanged={this.rowHasChanged.bind(this)}
        />
        <View style={styles.refreshIcon}>
          <TouchableOpacity onPress={() => this.agenda.chooseDay(new Date())}>
            <Icon.Circle
              type="refresh"
              size={40}
              color={white}
              backgroundColor={minorOrange}
            />
          </TouchableOpacity>
        </View>
      </View>
    );
  }

  loadItems(day) {
    setTimeout(() => {
      for (let i = -15; i < 85; i++) {
        const time = day.timestamp + i * 24 * 60 * 60 * 1000;
        const strTime = this.timeToString(time);
        if (!this.state.items[strTime]) {
          this.state.items[strTime] = [];
          const numItems = Math.floor(Math.random() * 5);
          for (let j = 0; j < numItems; j++) {
            eval(
              "var word=" +
                '"\\u' +
                (Math.round(Math.random() * 20901) + 19968).toString(16) +
                '"'
            );
            this.state.items[strTime].push({
              title: "五月份农户可能有贷款啊",
              subTitle:
                "时间：" +
                Math.ceil(Math.random() * 24) +
                ":00   客户：张" +
                word +
                word,
              state: Math.ceil(Math.random() * 4)
            });
          }
        }
      }
      //console.log(this.state.items);
      const newItems = {};
      Object.keys(this.state.items).forEach(key => {
        newItems[key] = this.state.items[key];
      });
      this.setState({
        items: newItems
      });
    }, 1000);
    // console.log(`Load Items for ${day.year}-${day.month}`);
  }
  renderItem(item) {
    console.log(item.state);
    let color = minorRed;
    switch (item.state) {
      case 1:
        color = minorRed;
        break;
      case 2:
        color = minorGreen;
        break;
      case 3:
        color = minorOrange;
        break;
      case 4:
        color = mainBlue;
        break;
    }
    let style = {
      backgroundColor: color
    };
    // Buttons
    let swipeoutBtns = [
      {
        text: "删除",
        backgroundColor:minorRed
      }
    ];
    return (
      <View style={styles.item}>
        <Swipeout right={swipeoutBtns} backgroundColor={white}>
          <View style={[styles.badge, style]} />
          <View>
            <Text style={styles.title}>
              {item.title}
            </Text>
          </View>
          <View>
            <Text style={styles.subTitle}>
              {item.subTitle}
            </Text>
          </View>
          <View>
            <View style={styles.operation}>
              <Text style={styles.operationText}>
                <Icon type="check-route" size={14} color={mainBlue} /> 查看路线
              </Text>
            </View>
          </View>
        </Swipeout>
      </View>
    );
  }

  renderEmptyDate() {
    return (
      <View style={styles.item}>
        <View style={styles.noScheduleView}>
          <View>
            <Icon type="noData" size={40} color={"#D8D8D8"} />
          </View>
          <TouchableOpacity>
            <View style={styles.addSchBtn}>
              <Text style={styles.addSchBtnText}>创建该日日程</Text>
            </View>
          </TouchableOpacity>
        </View>
      </View>
    );
  }

  rowHasChanged(r1, r2) {
    return r1.name !== r2.name;
  }

  timeToString(time) {
    const date = new Date(time);
    return date.toISOString().split("T")[0];
  }
}

export default Schedule;
`

**Comment by angularbaby** [comment]
```js
import React from "react";
import { Text, View, TouchableOpacity,PanResponder } from "react-native";
import styles from "./style";
import { Icon } from "../../../components";
import {
  mainBlue,
  minorGreen,
  minorOrange,
  minorRed,
  white
} from "../../../colors";
import { Agenda } from "react-native-calendars";
import Swipeout from "react-native-swipeout";

class Schedule extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      items: {},
      selected: new Date()
    };
  }

  render() {
    return (
      <View style={{ flex: 1 }}>
        <Agenda
          ref={agenda => {
            this.agenda = agenda;
          }}
          items={this.state.items}
          loadItemsForMonth={this.loadItems.bind(this)}
          selected={this.state.selected}
          renderItem={this.renderItem.bind(this)}
          renderEmptyDate={this.renderEmptyDate.bind(this)}
          rowHasChanged={this.rowHasChanged.bind(this)}
        />
        <View style={styles.refreshIcon}>
          <TouchableOpacity onPress={() => this.agenda.chooseDay(new Date())}>
            <Icon.Circle
              type="refresh"
              size={40}
              color={white}
              backgroundColor={minorOrange}
            />
          </TouchableOpacity>
        </View>
      </View>
    );
  }

  loadItems(day) {
    setTimeout(() => {
      for (let i = -15; i < 85; i++) {
        const time = day.timestamp + i * 24 * 60 * 60 * 1000;
        const strTime = this.timeToString(time);
        if (!this.state.items[strTime]) {
          this.state.items[strTime] = [];
          const numItems = Math.floor(Math.random() * 5);
          for (let j = 0; j < numItems; j++) {
            eval(
              "var word=" +
                '"\\u' +
                (Math.round(Math.random() * 20901) + 19968).toString(16) +
                '"'
            );
            this.state.items[strTime].push({
              title: "五月份农户可能有贷款啊",
              subTitle:
                "时间：" +
                Math.ceil(Math.random() * 24) +
                ":00   客户：张" +
                word +
                word,
              state: Math.ceil(Math.random() * 4)
            });
          }
        }
      }
      //console.log(this.state.items);
      const newItems = {};
      Object.keys(this.state.items).forEach(key => {
        newItems[key] = this.state.items[key];
      });
      this.setState({
        items: newItems
      });
    }, 1000);
    // console.log(`Load Items for ${day.year}-${day.month}`);
  }
  renderItem(item) {
    console.log(item.state);
    let color = minorRed;
    switch (item.state) {
      case 1:
        color = minorRed;
        break;
      case 2:
        color = minorGreen;
        break;
      case 3:
        color = minorOrange;
        break;
      case 4:
        color = mainBlue;
        break;
    }
    let style = {
      backgroundColor: color
    };
    // Buttons
    let swipeoutBtns = [
      {
        text: "删除",
        backgroundColor:minorRed
      }
    ];
    return (
      <View style={styles.item}>
        <Swipeout right={swipeoutBtns} backgroundColor={white}>
          <View style={[styles.badge, style]} />
          <View>
            <Text style={styles.title}>
              {item.title}
            </Text>
          </View>
          <View>
            <Text style={styles.subTitle}>
              {item.subTitle}
            </Text>
          </View>
          <View>
            <View style={styles.operation}>
              <Text style={styles.operationText}>
                <Icon type="check-route" size={14} color={mainBlue} /> 查看路线
              </Text>
            </View>
          </View>
        </Swipeout>
      </View>
    );
  }

  renderEmptyDate() {
    return (
      <View style={styles.item}>
        <View style={styles.noScheduleView}>
          <View>
            <Icon type="noData" size={40} color={"#D8D8D8"} />
          </View>
          <TouchableOpacity>
            <View style={styles.addSchBtn}>
              <Text style={styles.addSchBtnText}>创建该日日程</Text>
            </View>
          </TouchableOpacity>
        </View>
      </View>
    );
  }

  rowHasChanged(r1, r2) {
    return r1.name !== r2.name;
  }

  timeToString(time) {
    const date = new Date(time);
    return date.toISOString().split("T")[0];
  }
}

export default Schedule;

```

**Comment by angularbaby** [comment]
```js this.agenda.chooseDay(new Date())``` -> the _list_ Positioning is not accurate , _header_ accurate

**Comment by angularbaby** [comment]
Can you tell me what's the solution～～～🌹come on！

**Comment by tautvilas** [comment]
fixed in 1.5.7 :)

**Comment by andregufc** [comment]
I'm using the version @1.21.0 and I still facing this issue =/
The code is pretty similar to the presented above. Can you guys please check if your code is behaving correctly?
Thanks
