### ISSUE TITLE
Disabled days for interactive marking type

### ISSUE THREAD

**Issue by chapeljuice** [wix/react-native-calendars#200]
It would be awesome to add disabled days to the `interactive` marking types so we can mix and match styles.

Ideally I'd like to use the 'interactive' styles with the ending / start days, but also have some dates on the calendar that just have the strikethrough.

Something like the following

```
<Calendar
  // Collection of dates that have to be colored in a special way. Default = {}
   markedDates={
    {'2012-05-20': [{textColor: 'green'}],
     '2012-05-21': [{disabled: true}],    <--- THIS FEATURE WOULD BE NICE
     '2012-05-22': [{startingDay: true, color: 'green'}],
     '2012-05-23': [{endingDay: true, color: 'green', textColor: 'gray'}],
     '2012-05-04': [{startingDay: true, color: 'green'}, {endingDay: true, color: 'green'}]
    }}
  // Date marking style [simple/interactive]. Default = 'simple'
  markingType={'interactive'}
/>
```

Edit: It would also be super helpful to have something to check for to see if the day the user is pressing is a disabled day or not. :)

**Comment by tautvilas** [comment]
Resolved in version 1.10.0 marking structure for interactive was changed and now this marking type is called 'period' marking please, check README

**Comment by chapeljuice** [comment]
Hrm, I still don't see the ability to mix *strikethroughs* with the full color circle ... is that in the README and I'm just missing it?

**Comment by tautvilas** [comment]
currently disabled means just color change. previously this marking type did not support that
