### ISSUE TITLE
CalendarList rendering date string instead of calendar component even when it's fully visible

### ISSUE THREAD

**Issue by kiratot** [wix/react-native-calendars#2050]
## Description

I'm building a date range picker with CalendarList similar to [react-dates](https://github.com/react-dates/react-dates), I pass the starting date as the `current` date prop to the CalendarList component and I render everything in a modal with react-native-modal. The issue I was facing is when selecting the 31st day of a given month (all other days when selected work just fine), then I close the modal to reopen it again the current month was no longer visible and a date string is rendered instead. I've managed to dig around and have found that when its `visible` prop is false, the CalendarListItem component renders a date string e.g.: "2023-09-30". 
https://github.com/wix/react-native-calendars/blob/89bcf5bc159777ccf614ed545ac76a8605a621d9/src/calendar-list/item.tsx#L86-L106

The value of the `visible` prop is the returned result of this function: 
https://github.com/wix/react-native-calendars/blob/89bcf5bc159777ccf614ed545ac76a8605a621d9/src/calendar-list/index.tsx#L215-L223

So I have made some debugging and found that when the day of the month is 31, the `newMonth` variable is not what we expect it to be, and the XDate's `addMonths` function was causing an overflow issue. Luckily this is as straightforward to fix as passing `true` as a second argument to prevent the overflow from happening. Will make a pull request ASAP with the suggested fix.

## Expected Behavior

The current CalendarListItem should be visible if a date is in range.

## Observed Behavior

The current CalendarListItem was not rendered and a date string was visible instead.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`: react-native-calendars@1.1289.0
* `npm ls react-native`: 

│ └── react-native@0.70.0 deduped
├─┬ @openspacelabs/react-native-zoomable-view@2.0.4
│ └── react-native@0.70.0 deduped
├─┬ @react-native-async-storage/async-storage@1.17.10
│ └── react-native@0.70.0 deduped
├─┬ @react-native-picker/picker@2.4.4
│ └── react-native@0.70.0 deduped
├─┬ @react-navigation/material-bottom-tabs@6.2.3
│ ├─┬ @react-navigation/elements@1.3.5
│ │ └── react-native@0.70.0 deduped
│ ├─┬ react-native-paper@4.12.4
│ │ ├─┬ react-native-iphone-x-helper@1.3.1
│ │ │ └── react-native@0.70.0 deduped
│ │ └── react-native@0.70.0 deduped
│ └── react-native@0.70.0 deduped
├─┬ @react-navigation/material-top-tabs@6.2.3
│ └── react-native@0.70.0 deduped
├─┬ @react-navigation/native@6.0.12
│ └── react-native@0.70.0 deduped
├─┬ @react-navigation/stack@6.2.3
│ └── react-native@0.70.0 deduped
├─┬ @rnmapbox/maps@10.0.0-beta.36 (git+ssh://git@github.com/rnmapbox/maps.git#5b9605834113b98ceb76c17cebb37a5d8bd960e3)
│ └── react-native@0.70.0 deduped
├─┬ @segment/analytics-react-native@2.8.0
│ └── react-native@0.70.0 deduped
├─┬ @segment/sovran-react-native@0.4.4
│ └── react-native@0.70.0 deduped
├─┬ @stripe/stripe-react-native@0.19.0
│ └── react-native@0.70.0 deduped
├─┬ react-native-app-link@1.0.1
│ └── react-native@0.70.0 deduped
├─┬ react-native-blob-util@0.16.2
│ └── react-native@0.70.0 deduped
├─┬ react-native-bootsplash@4.3.2
│ └── react-native@0.70.0 deduped
├─┬ react-native-calendar-events@2.2.0
│ └── react-native@0.70.0 deduped
├─┬ react-native-calendars@1.1289.0
│ └─┬ recyclerlistview@3.0.5
│   └── react-native@0.70.0 deduped
├─┬ react-native-device-info@10.1.2
│ └── react-native@0.70.0 deduped
├─┬ react-native-fast-image@8.6.1
│ └── react-native@0.70.0 deduped
├─┬ react-native-fingerprint-scanner@6.0.0
│ └── react-native@0.70.0 deduped
├─┬ react-native-gesture-handler@2.6.0
│ └── react-native@0.70.0 deduped
├─┬ react-native-localize@2.2.3
│ └── react-native@0.70.0 deduped
├─┬ react-native-modal@13.0.1
│ └── react-native@0.70.0 deduped
├─┬ react-native-pager-view@6.0.0
│ └── react-native@0.70.0 deduped
├─┬ react-native-render-html@6.3.4
│ ├─┬ @jsamr/react-native-li@2.3.1
│ │ └── react-native@0.70.0 deduped
│ ├─┬ @native-html/transient-render-engine@11.2.3
│ │ └── react-native@0.70.0 deduped
│ └── react-native@0.70.0 deduped
├─┬ react-native-restart@0.0.24
│ └── react-native@0.70.0 deduped
├─┬ react-native-safe-area-context@4.3.3
│ └── react-native@0.70.0 deduped
├─┬ react-native-screens@3.17.0
│ └── react-native@0.70.0 deduped
├─┬ react-native-scroll-into-view@2.0.2
│ └── react-native@0.70.0 deduped
├─┬ react-native-svg-transformer@1.0.0
│ └── react-native@0.70.0 deduped
├─┬ react-native-svg@13.2.0
│ └── react-native@0.70.0 deduped
├─┬ react-native-tab-view@3.1.1
│ └── react-native@0.70.0 deduped
├─┬ react-native-version-check@3.4.3
│ └── react-native@0.70.0 deduped
├── react-native@0.70.0
├─┬ react-navigation-props-mapper@3.1.0
│ └── react-native@0.70.0 deduped
└─┬ react-redux@8.0.2
  └── react-native@0.70.0 deduped

Also specify:

1. Device/emulator/simulator & OS version: iOS Simulator of iPhone 13, iOS v15.0

## Screenshots: 

*When the current day date is 31:
![Simulator Screen Shot - iPhone 13 - 2022-09-29 at 16 51 20](https://user-images.githubusercontent.com/28838540/193066015-30e62877-57ef-4d88-8d3a-df24acbaf1a5.png)

*When the current day is other than 31: 

![Simulator Screen Shot - iPhone 13 - 2022-09-29 at 16 52 04](https://user-images.githubusercontent.com/28838540/193066307-0ec300c4-3827-4dcd-92c3-c4fef85aba74.png)

**Comment by kiratot** [comment]
I've merged the bug fix already @akramloginext, try updating to the latest version and see how it goes.

**Comment by sleekLancelot** [comment]
This bug still [exists on ios ](https://github.com/wix/react-native-calendars/issues/2299#issuecomment-2397072992)

**Comment by HexinJ** [comment]
The bug still exists on ios

**Comment by kiratot** [comment]
We're using "react-native-calendars": "1.1303.0" in production and the issue is not happening for iOS, being a travel company that relies heavily on the booking funnel and date selection from this calendar trust me we'd have noticed, try using the same version and see how it goes @HexinJ
