### ISSUE TITLE
Calendar doesn't update color if `selectedColor` is changed

### ISSUE THREAD

**Issue by ashumilov** [wix/react-native-calendars#359]
## Description

In `onDayPress` handler I add to `markedDates` selected day with properties `selected: true, selectedColor: "red"`. On the second selection of the previously selected day I just update `selectedColor: "blue"` (change color).

## Expected Behavior

Calendar should change color on `selectedColor` property change.

## Observed Behavior

Calendar doesn't change color on `selectedColor` property change. If I change `selected` property to `false` and then back to `true` calendar updates the color as expected.

## Environment

* `npm ls react-native-calendars`:
MyDays@0.1.0 /Users/sunnytigra/work/MyDays
└── react-native-calendars@1.17.2

* `npm ls react-native`:
MyDays@0.1.0 /Users/sunnytigra/work/MyDays
└── react-native@0.52.0

* iPhone SE, IOS 11.2.5
* iPhone Simulator SDK 11.2

## Reproducible Demo

Uncomment lines to work as supposed

```javascript
import React from 'react';
import Moment from 'moment'
const MomentRange = require('moment-range');
const moment = MomentRange.extendMoment(Moment);
import {Calendar} from 'react-native-calendars';

export default class App extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            markedDates: {}
        };
    }

    onDayPress = (day) => {
        const d = moment(day.dateString).format("YYYY-MM-DD")
        if (!this.state.markedDates[d]) {
            const color = 'red'
            const markedDates = {...this.state.markedDates,
                                 [d]: {
                                     selected: true,
                                     selectedColor: color}}
            this.setState({markedDates})
        } else {
//            const markedDates = {...this.state.markedDates,
//                                 [d]: {
//                                     ...this.state.markedDates[d],
//                                     selected: false}}
//            this.setState({markedDates}, () => {
                const color = this.state.markedDates[d].selectedColor == 'red' ? 'blue' : 'red'
                const markedDates = {...this.state.markedDates,
                                     [d]: {
                                         ...this.state.markedDates[d],
//                                         selected: true,
                                         selectedColor: color}}
                this.setState({markedDates})
//            })
        }
    }

    render () {
        return (
            <Calendar
                onDayPress={this.onDayPress}
                markedDates={this.state.markedDates}
            />
        )
    }
}
```

**Comment by AkshitSahani** [comment]
Hi, I'm encountering the exact same problem. The calendar does not update (re-render) if the selectedColor of a markedDate changes. The background color for the dates is not changing unless I press the left or right arrow key to change month (force re-rendering of the calendar).

<Calendar
style={{marginTop: 70}}
minDate={getDate()}
maxDate={getDate('max')}
hideExtraDays={true}
onDayPress={(day)=>{this.selectDate(day)}}
markedDates={this.state.selectedDates}
onMonthChange={(month)=>{this.nextMonth(month);}}
/>

selectDate = (day) => {
const {tappedDates} = this.state;
let updatedTappedDates = {...tappedDates};
if(updatedTappedDates[day.dateString] && updatedTappedDates[day.dateString] < 2){
updatedTappedDates[day.dateString] += 1;
}
else if(updatedTappedDates[day.dateString] === 2){
updatedTappedDates[day.dateString] = 0;
}
else{
updatedTappedDates[day.dateString] = 1;
}

this.setState({tappedDates: updatedTappedDates});

let color;
const calGreen = "#BFE9E6";
const calYellow = "#FBDC98";
const calRed = "#E7808D";

switch (updatedTappedDates[day.dateString]) {
  case 0:
    color = calGreen;
    break;
  case 1:
    color = calYellow;
    break;
  case 2:
    color = calRed;
    break;
  default:
    color = calGreen;
}

// const {selectedDates} = this.state;
// selectedDates = {...selectedDates, [day.dateString]: {selected: true, selectedColor: color}};
// this.setState({selectedDates});
-------if i write these two lines above, based on the solution you provided to vagnerSI, I get an 
            error saying "selectedDates is read-only"-------

// const {selectedDates} = this.state;
// let newSelectedDates = {...selectedDates, [day.dateString]: {selected: true, selectedColor: 
    color}};
// this.setState({selectedDates: newSelectedDates});
          ---- I tried this solution as well but not successful-------

let selectedDates = Object.assign({}, this.state.selectedDates);
selectedDates[day.dateString] = {selected: true, selectedColor: color};
this.setState({selectedDates: selectedDates});
 ------ I tried this solution as well after looking at some of your answers to other people having the 
            same problem, but this one is not successful either ----
};

**Comment by tautvilas** [comment]
solved in 1.18.0

**Comment by KirankumarDafda** [comment]
> "react-native": "0.57.3",
> "react-native-calendars": "^1.21.0",

I still have that problem, not able to re-render calendar on selectedColor change, I have tried above all examples and suggestions. 

Help me if anyone solved this.

**Comment by KirankumarDafda** [comment]
Hello, 
It was my mistake, I was setting new date like : 2019-1-28 which was not a valid date (don't know why) for marked date, when I set it as **2019-01-28** or **2019-01-02** it updates the date on calendar.

Anyway superb plugin thank you. 👍

**Comment by gurrenPizza** [comment]
> "react-native": "0.59.2",
    "react-native-calendars": "^1.32.0"

Hi, I'm facing this problem when I set the selected dates array on `componentDidMount` method. It behaves just as described by @AkshitSahani. 
Although @KirankumarDafda solved her problem by formatting her date strings/objects properly, mine already are. I only got to solve it by setting the array for `markedDates` on `render` method, but React Native console returns this error warning:

> Cannot update during an existing state transition (such as within `render`). 
Render methods should be a pure function of props and state.

Here's the important slice of the code:

```
render() {
        const { markedDates } = this.props;
        this.decorateDates(); // that's the function that defines the array
        return (            
                <View
                    style={styles.commonView}
                >
                        <Calendar
                            hideExtraDays
                            markedDates={markedDates}
                            style={styles.calendar}
                        />
                <View/>
       );
}
```

In the moment `decorateDates` is executed, the data needed to define the array is already stored in redux, so there's no async problem. Just to make sure, here's the redux payload that is being stored and then used by `decorateDates`:

```
payload:
2019-04-16: {selected: true, marked: true, selectedColor: "#2080FE"}
2019-04-18: {selected: true, marked: true, selectedColor: "#2080FE"}
2019-04-22: {selected: true, marked: true, selectedColor: "#CC1515"}
```
If I kept my code this way, it would still work, but it would create an unwanted situation in my application workflow. 
Have I done anything wrong? I hope I could give enough information

**Comment by danielkhaleb** [comment]
@tautvilas The problem is back in version:
   "react-native": "0.62.2"
    "react-native-calendars": "^1.300.0"
I changed to version 1.18.0 and there it works
