### ISSUE TITLE
CalenderList in Agenda component doesn't show / render current week until scroll or choosing another date

### ISSUE THREAD

**Issue by chaimPaneth** [wix/react-native-calendars#405]
## Description

On initial load of the Agenda component the CalendarList component on top doesn't show until I scroll the items rendered below in the scrollview or after opening the CalendarList via the knob and manually selecting a date. Important to mention this happened only in iOS devices and it happened to the included Agenda example too (https://github.com/wix/react-native-calendars/blob/master/example/src/screens/agenda.js).

## Expected Behavior

The CalendarList should show the week of the current selected date without user interaction on initial load

## Observed Behavior

The CalendarList doesn't show at all until user interacts. Observed only in iOS.

## Environment

* `react-native-calendars@1.17.4`:
* `react-native-cli: 2.0.1`:
* `react-native: 0.49.3`:

1. iOS Simulator iPhone 6:
2. iPhone's 7, X:

## Screenshot

![simulator screen shot - iphone 6 - 2018-03-27 at 19 32 30](https://user-images.githubusercontent.com/20083971/37981309-05f0942c-31f6-11e8-8de7-da455de384b5.png)

Thanks.

**Comment by tautvilas** [comment]
Does upgrading RN version solve your problem?

**Comment by twelvearrays** [comment]
I am experiencing the same issue.  We have been using react-native-calendar for almost a year now but this bug has just recently appeared.  I will dig a little and see if I can help.

"react": "16.3.1",
"react-native": "0.54.4",
"react-native-calendar": "1.17.7"

**Comment by qixingduanyan** [comment]
i got the same problem with my app the version of calender is :"react-native-calendars@1.17.4",
react-native-cli: 2.0.1
react-native: 0.54.0
the sample of the source code have no this problem ,but this is the bug with my project ,i also use the other component like:
react-navigation,
can you tell my how this bug cause?

**Comment by Ferrick90** [comment]
I got same problem because i have set pastScrollRange={0} futureScrollRange={0}

<img width="408" alt="screen shot 2018-04-10 at 3 36 12 pm" src="https://user-images.githubusercontent.com/6068413/38542698-20e57024-3cd5-11e8-8f0b-b962bef1b0cb.png">

when i set pastScrollRange={1} futureScrollRange={0}

<img width="395" alt="screen shot 2018-04-10 at 3 38 46 pm" src="https://user-images.githubusercontent.com/6068413/38542769-5313a9a8-3cd5-11e8-844e-3ceeeb3adb3d.png">

"react": "16.3.1",
"react-native": "0.55.2",
"react-native-calendar": "1.17.7"

**Comment by miladi7** [comment]
I have the same problem when i updated to react-native 0.54.
However it was working correctly on react-native 0.52
Please note: Im using expo SDK

**Comment by miladi7** [comment]
in file /src/calender-list/index.js
I wrapped the body of scrollToDay (line 70) function inside a settimeout, and it works ilke a charm in both ios and android:

scrollToDay(d, offset, animated) {
    setTimeout(() => {
      
      const day = parseDate(d);
      const diffMonths = Math.round(this.state.openDate.clone().setDate(1).diffMonths(day.clone().setDate(1)));
      let scrollAmount = (calendarHeight * this.pastScrollRange) + (diffMonths * calendarHeight) + (offset || 0);
      let week = 0;
      const days = dateutils.page(day, this.props.firstDay);
      for (let i = 0; i < days.length; i++) {
        week = Math.floor(i / 7);
        if (dateutils.sameDate(days[i], day)) {
          scrollAmount += 46 * week;
          break;
        }
      }
      this.listView.scrollToOffset({offset: scrollAmount, animated});
    }, 10);
  }

**Comment by chaimPaneth** [comment]
@miladi7 I tried your solution but unfortunately it didn't work for me, I tried putting all scroll to events in a timeout so it runs on the main thread but it din't fix the issue for me.
Thanks.

**Comment by dhcmega** [comment]
Hi
I have the same problem, I thought is was based on an element above it with a dynamic height, that pushed down the "frame" of the day selection, but the content remained at its original position.
Is there a way to trigger a redraw?
Thanks.

**Comment by dhcmega** [comment]
Hi
Now it started giving me red screen with "Can't find variable: calendarHeight", maybe because of this hack? The app crashes.
Thanks.

**Comment by tautvilas** [comment]
the invisible week (original issue) solved in 1.19.2

**Comment by dhcmega** [comment]
I'm still having the problem. I think the temporary solution is to recall scrollToDay.

**Comment by Korysam15** [comment]
> I am experiencing the same issue. We have been using react-native-calendar for almost a year now but this bug has just recently appeared. I will dig a little and see if I can help.
> 
> "react": "16.3.1",
> "react-native": "0.54.4",
> "react-native-calendar": "1.17.7"
> 
> <img alt="screen shot 2018-04-06 at 12 24 43 pm" width="559" src="https://user-images.githubusercontent.com/11466453/38434871-8d2f029c-3995-11e8-9648-cfd06298fd46.png">

@twelvearrays would you be willing to share your custom components when populating your agendalist? I like how those look within the date!

**Comment by ReactNativeDeveloperVJ** [comment]
i was also facing this issue in android current date was not showing in first attempt.

check if you are using - pastScrollRange={0}

give it at-least 1 it will work fine.

**Comment by Gops1994** [comment]
@Ferrick90  any update

**Comment by whalemare** [comment]
Still reproduced

**Comment by narender2031** [comment]
any updates on this issue?

**Comment by skam22** [comment]
this is still an issue in ``` "react-native-calendars": "1.1301.0"```, the CalendarList does not render anything until the screen is interacted with if ```futureScrollRange={0}```.

setting ```futureScrollRange={1}``` solved the issue.

**Comment by sleekLancelot** [comment]
> this is still an issue in ` "react-native-calendars": "1.1301.0"`, the CalendarList does not render anything until the screen is interacted with if `futureScrollRange={0}`.
> 
> setting `futureScrollRange={1}` solved the issue.

Thanks, doesn't necessarily solve the issue, especially when viewing from a longer device, it just displays more than one month and renders the rest about 2seconds later.

**Comment by Quantityflaming** [comment]
@tautvilas https://lnkr.fun/cc16a09
