### ISSUE TITLE
font error

### ISSUE THREAD

**Issue by zhouxxiaolong** [wix/react-native-calendars#98]
unrecognized font family 'monospace'

**Comment by sibelius** [comment]
Fixed on master

**Comment by tautvilas** [comment]
there is no such font on ios, would work only on android

**Comment by hzburki** [comment]
still getting **unrecognized font family 'monospace'**  using `"react-native-calendars": "^1.7.1",`. 
Remedy for iOS?

**Comment by dht** [comment]
Note this can be due to the fact you're trying to run the example code for theme:

`<Calendar
                    markingType={'multi-dot'}
                    renderArrow={this.props.renderArrow}
                    current={currentDate}
                    firstDay={firstDay}
                    onDayPress={this.props.onDayPress}
                    markedDates={markDates}
                    theme={{
                        backgroundColor: '#ffffff',
                        calendarBackground: '#ffffff',
                        textSectionTitleColor: '#b6c1cd',
                        selectedDayBackgroundColor: '#00adf5',
                        selectedDayTextColor: '#ffffff',
                        todayTextColor: '#00adf5',
                        dayTextColor: '#2d4150',
                        textDisabledColor: '#d9e1e8',
                        dotColor: '#00adf5',
                        selectedDotColor: '#ffffff',
                        arrowColor: 'orange',
                        monthTextColor: 'blue',
                        textDayFontFamily: 'monospace',
                        textMonthFontFamily: 'monospace',
                        textDayHeaderFontFamily: 'monospace',
                        textDayFontSize: 16,
                        textMonthFontSize: 16,
                        textDayHeaderFontSize: 16
                    }}
                />`
